name: genesis
channels:
  - robostack-staging
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.14
  - aiohttp-cors=0.7.0
  - aiosignal=1.4.0
  - ampl-asl=1.0.0
  - annotated-types=0.7.0
  - asttokens=3.0.0
  - attrs=25.3.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.7.14
  - cachetools=5.5.2
  - cffi=1.17.1
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - colorful=0.5.6
  - comm=0.2.2
  - cryptography=45.0.5
  - deap=1.4.3
  - debugpy=1.8.14
  - decorator=5.2.1
  - deprecated=1.2.18
  - distlib=0.3.9
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - filelock=3.18.0
  - frozenlist=1.7.0
  - google-api-core=2.25.1
  - google-auth=2.40.3
  - googleapis-common-protos=1.70.0
  - grpcio=1.71.0
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipopt=3.14.17
  - ipykernel=6.29.5
  - ipyparallel=9.0.1
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jsonschema-specifications=2025.4.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libabseil=20250127.1
  - libblas=3.9.0
  - libboost=1.86.0
  - libcblas=3.9.0
  - libedit=3.1.20250104
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libgrpc=1.71.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libopenblas=0.3.29
  - libprotobuf=5.29.3
  - libre2-11=2025.06.26
  - libscotch=7.0.4
  - libsodium=1.0.20
  - libspral=2025.03.06
  - libsqlite=3.49.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libunwind=1.8.2
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.13.8
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - metis=5.1.0
  - msgpack-python=1.1.1
  - multidict=6.6.3
  - mumps-include=5.7.3
  - mumps-seq=5.7.3
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlopt=2.10.0
  - numpy=2.2.5
  - opencensus=0.11.3
  - opencensus-context=0.1.3
  - openssl=3.5.1
  - opentelemetry-api=1.35.0
  - opentelemetry-exporter-prometheus=0.48b0
  - opentelemetry-proto=1.35.0
  - opentelemetry-sdk=1.35.0
  - opentelemetry-semantic-conventions=0.56b0
  - packaging=25.0
  - pagmo=2.19.1
  - pandas=2.2.3
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1
  - pkgutil-resolve-name=1.3.10
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - propcache=0.3.1
  - proto-plus=1.26.1
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-spy=0.4.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pybind11-abi=4
  - pycparser=2.22
  - pygmo=2.19.7
  - pyopenssl=25.1.0
  - pysocks=1.7.1
  - python=3.11.12
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - pyzmq=27.0.0
  - ray-core=2.47.1
  - ray-default=2.47.1
  - re2=2025.06.26
  - readline=8.2
  - referencing=0.36.2
  - rsa=4.9.1
  - setproctitle=1.3.6
  - setuptools=79.0.1
  - six=1.17.0
  - smart_open=7.3.0.post1
  - stack_data=0.6.3
  - tbb=2022.1.0
  - tk=8.6.13
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-inspection=0.4.1
  - typing_extensions=4.14.1
  - tzdata=2025b
  - virtualenv=20.31.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - wrapt=1.17.2
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.20.1
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.2.2
      - anyio==4.9.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.1
      - click==8.1.8
      - coacd==1.0.6
      - colorlog==6.9.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - dill==0.4.0
      - embreex==2.17.7.post6
      - etils==1.12.2
      - fonttools==4.57.0
      - freetype-py==2.5.1
      - fsspec==2025.3.2
      - genesis-world==0.2.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glfw==2.9.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - jinja2==3.1.6
      - jsonschema==4.23.0
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - libigl==2.5.1
      - llvmlite==0.44.0
      - manifold3d==3.1.0
      - mapbox-earcut==1.0.3
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - moviepy==2.1.2
      - mpmath==1.3.0
      - mujoco
      - mypy-extensions==1.1.0
      - networkx==3.4.2
      - numba==0.61.2
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - ompl==1.7.0
      - onnx==1.17.0
      - opencv-python==4.11.0.86
      - openexr==3.3.3
      - pillow==10.4.0
      - platformdirs==4.3.7
      - plotly==5.24.1
      - pooch==1.8.2
      - proglog==0.1.11
      - protobuf==6.30.2
      - py-cpuinfo==9.0.0
      - pycollada==0.9
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pygel3d==0.6.1
      - pyglet==2.1.6
      - pygltflib==1.16.0
      - pygments==2.19.1
      - pymeshlab==2023.12.post3
      - pyopengl==3.1.9
      - pyparsing==3.2.3
      - python-dotenv==1.1.0
      - pyvista==0.45.0
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.25.0
      - rsl-rl-lib==2.2.4
      - rtree==1.4.0
      - scikit-image==0.25.2
      - scipy==1.15.2
      - scooby==0.10.1
      - shapely==2.1.1
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - svg-path==6.3
      - sympy==1.14.0
      - taichi==1.7.3
      - tenacity==9.1.2
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tetgen
      - tifffile==2025.3.30
      - torch==2.7.0
      - torchvision==0.22.0
      - trimesh==4.6.8
      - triton==3.3.0
      - typer==0.12.5
      - typing-extensions==4.13.2
      - typing-inspect==0.9.0
      - urllib3==2.4.0
      - vhacdx==0.0.8.post2
      - vtk==9.4.2
      - watchdog==4.0.2
      - werkzeug==3.1.3
      - xxhash==3.5.0
      - yourdfpy==0.0.57
      - z3-solver==4.15.0.0
      - zipp==3.21.0

